name: PR validation

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.9
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.9"
          cache: "poetry"
          cache-dependency-path: "poetry.lock"

      - name: Install dependencies
        run: poetry install

      - name: Run code linters
        run: |
          poetry run ruff check .
          poetry run black --check .

      - name: Lint commits
        run: |
          poetry run cz check --rev-range origin/${GITHUB_BASE_REF}..
